### ISSUE TITLE
Download Replays only

### ISSUE THREAD

**Issue by godofgrunts** [fgcreplaymiyoka/fgc-replay-miyoka#13]
Fantastic project! I have a tangential use case where I only need to download replays. For context, I help run Street Fighter online events for a discord group and I like to compile all the offline matches that don't get streamed.

Is there anyway to avoid setting up the gcloud stuff and download a bunch of replays based on replay IDs that I give it?

**Comment by fgcreplaymiyoka** [comment]
@godofgrunts Interesting use case.

I'm a bit confused since you mention online event but compile offline matches. Perhaps you meant downloading online matches for the online tournament regardless of it's streamed on the main streaming channel? As long as the matches are happening on online, which leaves the replays on CFN, the proposed feature can be implemented.

**Comment by godofgrunts** [comment]
@fgcreplaymiyoka I misspoke. By "offline" matches I did mean ones that weren't on the stream.

Here is the playlist for the last event we did: https://www.youtube.com/playlist?list=PLN04hXWCbd9_TADWH_QxBZakIzhkuPbI7

As you can see there was almost 4 hours of off stream matches that I recorded manually which would be so nice if I could automate that part.

**Comment by godofgrunts** [comment]
I think your program currently works by grabbing my name and only downloading my replays, but I would need to supply a bunch of replay IDs. Not sure if that's outside the scope of this project or not.

**Comment by fgcreplaymiyoka** [comment]
@godofgrunts

If you can collect replay IDs manually (e.g. `ABCDXQPDH`), then I can add a mode that records the replays and export it to a local computer's storage. In this case, the config.yaml would look like:

Replay ID base:

```
game:
  name: sf6
  window:
    name: Street Fighter 6
  replay_ids:
    -  ABCDXQPDH
    -  CBADXQPDH
```

I recently added a feature to allow users to specify multiple user code. If it works for you, then the config would look like:

```
game:
  name: sf6
  window:
    name: Street Fighter 6
  players:
    # `name`: Name of the player displayed in replay viewer.
    # `id`: Identifier of the player in the game. Replay Uploader crawls replays associated with the ID in the game.
    # `pattern`: Pattern of the player name in the game. This is used to filter the replay dataset for each player.
    - name: Player-A
      id: Player-A-user-code
    - name: Player-B
      id: Player-B-user-code
```

In this case, you need to manually filter tournament or non-tournament matches, such as casual and ranked.
